### ISSUE TITLE
gh-pages branches

### ISSUE THREAD

**Issue by rkdarst** [ResearchSoftwareHour/researchsoftwarehour.github.io#45]
Now, we can configure an arbitrary branch for gh-pages (part of the slow process of renaming default branch...)

should we rename "master" to "gh-pages", and "source" to "master", and set gh-pages as the branch to publish?  Would that work?

**Comment by bast** [comment]
Yes, good idea. I will do that. (`main` instead of `master` since that's the new default on GH).

**Comment by bast** [comment]
Done. Seems to work.
